"""empty message

Revision ID: 212b4691aef3
Revises: 
Create Date: 2021-01-22 14:52:02.080660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212b4691aef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('posters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=45), nullable=False),
    sa.Column('md5_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posters')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_posters_md5_hash'))
    )
    op.create_table('roles5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles5'))
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('production_year', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('screenwriter', sa.String(length=100), nullable=False),
    sa.Column('actors', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['posters.id'], name=op.f('fk_movies_poster_id_posters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    op.create_table('users5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles5.id'], name=op.f('fk_users5_role_id_roles5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users5')),
    sa.UniqueConstraint('login', name=op.f('uq_users5_login'))
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genres_movie_id_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('pk_movie_genres'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_reviews_movie_id_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['users5.id'], name=op.f('fk_reviews_user_id_users5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('movie_genres')
    op.drop_table('users5')
    op.drop_table('movies')
    op.drop_table('roles5')
    op.drop_table('posters')
    op.drop_table('genres')
    # ### end Alembic commands ###
