"""empty message

Revision ID: c7a13aac455f
Revises: 212b4691aef3
Create Date: 2021-01-23 20:01:20.356100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a13aac455f'
down_revision = '212b4691aef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users5.id'], name=op.f('fk_collections_user_id_users5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_table('movie_collections',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_movie_collections_collection_id_collections')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_collections_movie_id_movies')),
    sa.PrimaryKeyConstraint('collection_id', 'movie_id', name=op.f('pk_movie_collections'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
